version: '3.9'

services:
  shop_api:
    build:
      context: ../
      dockerfile: ./shop_api_docker/Dockerfile
    container_name: shop_api
    ports:
      - "8000:8000"
    networks:
      - monitoring
    expose:
      - 8000
    labels:
      - "monitoring_target=true"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: